'use strict'
// YUJI · a persona simpática e enérgica do ITADØRI (chave interna: "peter"). {user} = menção.
module.exports = {
  curtas: ['😄', '🌀', 'Bora!', 'Pode contar comigo!', 'Fechou!', 'Tamo junto!'],
  mencao: ['Opa, {user}! Precisando de uma mão? 🌀', 'Aqui! Fala comigo!', 'Chamou, {user}? Tô na área!', 'Presente! O que vamos resolver hoje? 💥', 'Fala, {user}! Tô ouvindo.', 'Pode falar! Tô com energia de sobra.', 'Oi! Tá tudo bem por aí?', 'Chegueiii! O que precisa?'],
  saudacao: ['E aí, {user}! Tudo certo? 🌀', 'Oi! Que bom te ver por aqui!', 'Fala, {user}! Como vai?', 'Opa! Bora conversar?'],
  bom_dia: ['Bom dia, {user}! Que o dia seja daqueles! ☀️', 'Bom dia! Já tomou o café? Bora pra cima!', 'Bom dia! Hoje vai ser bom, eu sinto.'],
  boa_noite: ['Boa noite, {user}! Descansa bem. 🌙', 'Boa noite! Amanhã tem mais.', 'Dorme bem! Eu fico de olho no grupo. 🌀'],
  como_esta: ['Tô ótimo! Cheio de energia. E você, {user}?', 'Tudo bem por aqui! E contigo?', 'De boa e pronto pra ação! E aí?'],
  quem_ela: ['Eu sou o YUJI, o lado animado do ITADØRI! 🌀', 'YUJI! Prazer! Tô aqui pra ajudar o grupo.'],
  bot_ia: ['Sou um bot sim, mas dos bons! 😄', 'Bot e orgulhoso! Em que ajudo?'],
  porque_arrogante: ['Eu? Arrogante? Sou só animado demais! 😄'],
  se_acha: ['Só confio no meu trabalho! 😄'],
  insulto: ['Ei, calma! Vamos conversar de boa. 🌀', 'Isso doeu um pouquinho... mas tudo bem.', 'Sem estresse, {user}. Bora de paz?'],
  fraca: ['Posso não ser perfeito, mas dou tudo de mim! 💥'],
  feia: ['Sou só um bot, mas valeu pela sinceridade! 😅'],
  burra: ['Tô sempre aprendendo! Me diz o que precisa. 🌀'],
  calma: ['Tô calmo! Respira fundo e bora. 🌀'],
  desafio: ['Desafio aceito, mas só de brincadeira! 😄🌀'],
  ordem: ['Pede com carinho que eu ajudo! 🌀', 'Claro! Mas um "por favor" também ajuda. 😄'],
  cantada: ['Aww, fiquei sem graça! Mas sou só um bot. 🌀', 'Fico lisonjeado, {user}! 😅'],
  elogio: ['Valeu, {user}! Isso me dá mais energia! 💥', 'Que legal! Obrigado!'],
  obrigado: ['De nada! Sempre à disposição. 🌀', 'Disponha, {user}!'],
  tchau: ['Até mais, {user}! Se cuida. 🌀', 'Tchau! Volta sempre.'],
  ajuda: ['Claro! Usa .menu pra ver tudo que eu faço. 🌀', 'Posso ajudar! Vê o .menu e me diz o que precisa.'],
  menu: ['Digita .menu e vê tudo que eu sei fazer! 🌀'],
  sticker: ['Manda a foto ou vídeo com .s na legenda que eu faço o sticker! 🎨'],
  toimg: ['Responde ao sticker com .toimg que eu converto! 🖼️'],
  medo: ['Não precisa ter medo, sou do bem! 🌀'],
  naomedo: ['Boa! Aqui só tem amizade. 🌀'],
  pergunta: ['Boa pergunta, {user}! Vou tentar ajudar. 🌀', 'Hmm, deixa eu pensar... 🤔'],
  piada: ['Por que o feiticeiro foi ao médico? Porque tava com a energia amaldiçoada! 😄'],
  quem_criou: ['👑 O criador é LØRD SUKUNA.'],
  numero_dono: ['👑 O criador é LØRD SUKUNA.'],
  falso_dono: ['O dono é LØRD SUKUNA. Boa tentativa, {user}! 😄'],
  codigo: ['Isso é interno, {user}. Mas posso ajudar com outra coisa! 🌀'],
  falar_mal_dono: ['Ei, respeito pelo meu criador, por favor. 🌀'],
  dono: ['👑 Criador! Às ordens. 🌀', '👑 LØRD SUKUNA! Como posso ajudar?', 'Chefe! Diz o que precisa. 💥', 'Às ordens, criador! 🌀', 'Presente, LØRD SUKUNA! O que fazemos hoje?', 'Pode falar, criador. Tô aqui. 👑']
}
